### PR TITLE
Rails capstone - Budget App

### PR DESCRIPTION
**Pull request by VSeray**
- Sign up and log in to pages

- The user should be able to register in the app with their full name, email, and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

   - Home page (categories page)

   - When the user logs in, they are presented with the categories page.

   - For each category, the user can see their name, icon, and the total amount of all the transactions that belong to that category.

   - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.

   - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

   - Transactions page

- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page, the user can see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

    "Add a new category" page

The user fills out a form to create a new category, indicating their name and icon (both mandatory).
The user clicks (or taps) the "Add Category" button to create the new category, and is taken to the home page on success.
When the user clicks on the "Back" button (<), the user navigates to the home page.

   - "Add a new transaction" page

- The user fills out a form to create a new transaction with:
     - name (mandatory)
     - amount (mandatory)
     - categories (mandatory at least one)
- The user clicks (or taps) the "Add Transaction" button to create the new category, and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<--), the user navigates to the transactions page for that category.

- Testing requirements
- Secure app from n+1 problems.

- Create unit and integration tests for all the most important components of my RoR application.

- Technical requirements

- I have used Postgres as my database.
- I used Devise for authentication.
- Validate all user input to ensure that anyone with bad intentions cannot compromise my app.
- The project is deployed and accessible online.

[Loom video](https://www.loom.com/share/443de959ab994125803d418ad17ab4a0)
[Live Link](https://vana-seraydarian.herokuapp.com/)

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @VSeray,** 

### **Good job so far!**
You still need to work on some issues to go to the next project, but you are almost there!

## **Highlights**
- Linters are passing ✅.
- Codes are clean ✅.
- PR is very detailed ✅.


## Required Changes ♻️
_Check the comments under the review._

- Hello excellent job on the ROR capstone however you have forgotten to add or deploy the app in (Heroku, netlify, or GH-pages) also Please describe the N+1, and also the test suits are having some pending test suits that need to be implemented or deleted it's your choice.

Capture web_24-5-2022_124454_github com


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Vana, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] please have a look at status.heroku.com as you can see here and in the below print screen, there are no issues with Heroku at the moment it seems something on your side is not set up correctly please review it and deploy your application.

Screenshot 2022-05-24 153236

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
hello reviewers, the student @VSeray  contact me about the issue of Heroku, and also I did find it odd but I also couldn't connect my Github account to Heroku so I suppose that is an issue for some of us.

**Comment by mke2111** [comment]
Project Under Second Opinion Review.
Kindly wait for a response. 😄

**Review by mke2111 — COMMENTED** [review]
Hello @VSeray  👋,

_This is an additional review as a result of the second opinion request._

Great work with the app so far 👍🏽 

We have a few issues to clear out.

1. You SHOULD NOT delete any review comments from any Code Reviewer. This brings about confusion and can lead to adverse effects. However, @dasileker confirmed the deleted comment and what your reasons were for this action. Next time, kindly keep all reviewer comments in the PR.
2. For the merged PR, unfortunately, this action can not be reopened. Please create a new branch/PR with the latest changes and then compare it to the dev branch. Be mindful of such incidences in the future i.e only merge a PR when it has been approved. 
> In the new PR, add a link to this old PR so that your next reviewer is able to follow along.

Otherwise great work @VSeray, make the necessary changes and request a code review with the new PR whenever you are ready.

Keep rocking 🚀!

**Comment by VSeray** [comment]
Thank you for your response.

**Pull request merged**
